###############################################################
#################---application-service.yml---##################
###############################################################
# 当前项目业务配置
## 通用配置-文件路径 示例（ Windows配置D:/data/file/loadpath，Linux配置 /data/file/loadpath）
jeemodel.solution.file.profile: E:/data/file/loadpath


# 代码生成:jeemodel-unit-manage
# 防止XSS攻击
## 过滤开关
jeemodel.unit.manage.core.xss.enabled: true
## 排除链接（多个用逗号分隔）
jeemodel.unit.manage.core.xss.excludes: /manage/notice
## 匹配链接
jeemodel.unit.manage.core.xss.urlPatterns: /manage/*,/monitor/*,/coding/gen/*

# Swagger配置
## 是否开启swagger
jeemodel.unit.manage.core.swagger.enabled: true
## 请求前缀
jeemodel.unit.manage.core.swagger.pathMapping: /dev-api

# token配置
## 令牌自定义标识
jeemodel.unit.manage.core.token.header: Authorization
## 令牌密钥 秘钥(普通字符串) 不能太短，太短可能会导致报错
jeemodel.unit.manage.core.token.secret: wQW1RDuu4sL5LVlpIvDyMtfp1xBL6tCIj5Pvq7dVxZjUgUVX7jjEglRKPc4uHjn4wQW1RDuu4sL5LVlpIvDyMtfp1xBL6tCIj5Pvq7dVxZjUgUVX7jjEglRKPc4uHjn4wQW1RDuu4sL5LVlpIvDyMtfp1xBL6tCIj5Pvq7dVxZjUgUVX7jjEglRKPc4uHjn4wQW1RDuu4sL5LVlpIvDyMtfp1xBL6tCIj5Pvq7dVxZjUgUVX7jjEglRKPc4uHjn4
## 令牌有效期（默认30分钟）
jeemodel.unit.manage.core.token.expireTime: 30

## 验证码类型
jeemodel.unit.manage.system.captcha.type: 0


# 代码生成:jeemodel-unit-gen
## 作者
jeemodel.unit.gen.coding.author: JeeModel
## 默认生成包路径 manage 需改成自己的模块名称 如 manage gen
jeemodel.unit.gen.coding.packageName: com.jeemodel.unit.manage
## 自动去除表前缀，默认是false
jeemodel.unit.gen.coding.autoRemovePre: true
## 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
jeemodel.unit.gen.coding.tablePrefix: manage_,gen_,
## 默认上级菜单，研发工具
jeemodel.unit.gen.coding.defaultParentMenuName: 拓展功能



